### ISSUE TITLE
Task List Front End 

### ISSUE THREAD

**Issue by Zihaokong** [Zihaokong/cse110-w21-group27#5]
## Description:
What the task list page should mostly look like. Front end design of task list page without header, Decent CSS needed.

- [x] add task button
- [x] three sample tasks
- [x] checkmark
- [x] progress bar
- [x] start button
- [x] setting button
- [x] CSS of task list page

Leave some room for header with Ray.
