### ISSUE TITLE
Task List - JS Functions 

### ISSUE THREAD

**Issue by Zihaokong** [Zihaokong/cse110-w21-group27#6]
## Descriptions:
Implement interaction functions such as drag, modal, form mainly with Javascript or occasionally using CSS.

- [x] Modal form with task name, estimate, notes
- [x] Functionality of checkmark
- [x] Functionality of start button
- [x] Functionality of "option" button
- [x] Delete Task
- [x] cancel button
Confusion can be resolved by asking Design team.
